### ISSUE TITLE
Display results of filtered search

### ISSUE THREAD

**Issue by nguyenluke25** [G9-W2022-COMP231/OurRecipes#13]

**Comment by JameeKim** [comment]
Taking this over to finish a high-priority task

**Comment by JameeKim** [comment]
Decided to wait for #10 because it is suspected that additional tweaking will be required for this task after that task is implemented.

**Comment by JameeKim** [comment]
- Estimated: 1.5 hours
- Actual: 0.5 hours

Note:
Done by a different person
