### ISSUE TITLE
Display recipe details

### ISSUE THREAD

**Issue by nguyenluke25** [G9-W2022-COMP231/OurRecipes#19]

**Comment by JameeKim** [comment]
Currently blocked by #18

**Comment by JameeKim** [comment]
- Estimated: 0.5 hours
- Actual: 2 hours

Note:

1. When making the estimate, I overlooked the complexity of the data to be handled for this task.
2. The code for UI made it more difficult for me to find the right parts to plug in the data. I spent most of the time trying to figure out what is going on and why the UI is looking so different from the paper prototype. I strongly suggest actively creating React components to organize the code structure and improve readability.
3. There were some discrepancies between the type definitions for the data written in our code and the actual data returned by the API. But this was a minor issue that I spent only 10 minutes on.
