### ISSUE TITLE
Make request to server to search for recipe

### ISSUE THREAD

**Issue by nguyenluke25** [G9-W2022-COMP231/OurRecipes#3]

**Comment by JameeKim** [comment]
The server-side handling of the request, implemented in #59, assumes that the request is sent to the url of the form `https://host.address/?q=titleSearch&p=pageNumber` where the page number is optional and defaults to `0` (first page). Sending request to trigger this server-side handler is easily achieved by making the search form have the `method` of `"get"` and making the `name` attribute of the text input field `"q"`. In case we get to implement pagination too, the page number should have the name of `"p"`.
