### ISSUE TITLE
Response from server for user information

### ISSUE THREAD

**Issue by nguyenluke25** [G9-W2022-COMP231/OurRecipes#52]

**Comment by JameeKim** [comment]
Currently blocked by #23 or #31

**Comment by JameeKim** [comment]
Starting to work on this since #19 is blocked

**Comment by JameeKim** [comment]
- Estimated: 1 hour
- Actual: 0.5 hours

Note:
I thought I would need to access the database directly, but it turned out a utility I created when implementing authentication did all that job for me.
